from __future__ import annotations

from collections import Counter
from pathlib import Path

from engine_revival.indexer import TargetSummary, build_target_index, render_target_table
from engine_revival.records import load_records


HEADER = "<!-- generated by engine-revival report -->\n\n"


def _write(path: Path, body: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER + body, encoding="utf-8")
    return path


def _rights_summary(targets: list[TargetSummary]) -> str:
    counts = Counter(target.rights_posture for target in targets)
    lines = ["# Rights Summary", "", "| Rights posture | Count |", "|---|---:|"]
    for posture, count in sorted(counts.items()):
        lines.append(f"| {posture} | {count} |")
    return "\n".join(lines) + "\n"


def _artifact_summary(root: Path) -> str:
    if not (root / "artifacts").exists():
        return "# Artifacts\n\nNo artifact records yet.\n"
    lines = [
        "# Artifacts",
        "",
        "| Target | Artifact | Type | Status | Access |",
        "|---|---|---|---|---|",
    ]
    for record in load_records(root, "artifact"):
        payload = record.payload
        lines.append(
            f"| {payload['target_id']} | {payload['title']} | {payload['artifact_type']} | "
            f"{payload['redistribution_status']} | {payload['access_level']} |"
        )
    return "\n".join(lines) + "\n"


def _accession_summary(root: Path) -> str:
    if not (root / "accessions").exists():
        return "# Accessions\n\nNo accession records yet.\n"
    lines = [
        "# Accessions",
        "",
        "| Artifact | Package | Capture | Fixity | Storage | Rights | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    records = sorted(
        load_records(root, "accession"),
        key=lambda record: (record.payload["artifact_id"], record.payload["id"]),
    )
    for record in records:
        payload = record.payload
        lines.append(
            f"| {payload['artifact_id']} | {payload['package_type']} | "
            f"{payload['capture_status']} | {payload['fixity_status']} | "
            f"{payload['storage_class']} | {payload['rights_review']} | {payload['public_notes']} |"
        )
    return "\n".join(lines) + "\n"


def _task_summary(root: Path) -> str:
    if not (root / "tasks").exists():
        return "# Tasks\n\nNo task records yet.\n"
    lines = [
        "# Tasks",
        "",
        "| Target | Task | Type | Status | Notes |",
        "|---|---|---|---|---|",
    ]
    records = sorted(
        load_records(root, "task"),
        key=lambda record: (record.payload["target_id"], record.payload["id"]),
    )
    for record in records:
        payload = record.payload
        lines.append(
            f"| {payload['target_id']} | {payload['id']} | {payload['task_type']} | "
            f"{payload['status']} | {payload['public_notes']} |"
        )
    return "\n".join(lines) + "\n"


def write_reports(root: Path) -> list[Path]:
    targets = build_target_index(root)
    generated = root / "docs" / "generated"
    return [
        _write(generated / "index.md", "# Engine Revival Public Index\n\n" + render_target_table(targets)),
        _write(generated / "targets.md", "# Targets\n\n" + render_target_table(targets)),
        _write(generated / "rights-summary.md", _rights_summary(targets)),
        _write(generated / "artifacts.md", _artifact_summary(root)),
        _write(generated / "accessions.md", _accession_summary(root)),
        _write(generated / "tasks.md", _task_summary(root)),
    ]
