from __future__ import annotations

from collections import Counter
import json
from pathlib import Path

from engine_revival.indexer import TargetSummary, build_target_index, render_target_table
from engine_revival.records import load_records
from engine_revival.report_corpus import (
    corpus_database,
    packet_index,
    packet_page,
    packet_tasks,
    reproduction_index,
    reproduction_page,
    reproduction_records,
    snapshot_index,
    snapshot_page,
    snapshot_records,
)
from engine_revival.report_targets import target_dossier


HEADER = "<!-- generated by engine-revival report -->\n\n"


def _write(path: Path, body: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER + body, encoding="utf-8")
    return path


def _write_json(path: Path, payload: dict[str, object]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, sort_keys=True) + "\n", encoding="utf-8")
    return path


def _rights_summary(targets: list[TargetSummary]) -> str:
    counts = Counter(target.rights_posture for target in targets)
    lines = ["# Rights Summary", "", "| Rights posture | Count |", "|---|---:|"]
    for posture, count in sorted(counts.items()):
        lines.append(f"| {posture} | {count} |")
    return "\n".join(lines) + "\n"


def _artifact_summary(root: Path) -> str:
    if not (root / "artifacts").exists():
        return "# Artifacts\n\nNo artifact records yet.\n"
    lines = [
        "# Artifacts",
        "",
        "| Target | Artifact | Type | Status | Access |",
        "|---|---|---|---|---|",
    ]
    for record in load_records(root, "artifact"):
        payload = record.payload
        lines.append(
            f"| {payload['target_id']} | {payload['title']} | {payload['artifact_type']} | "
            f"{payload['redistribution_status']} | {payload['access_level']} |"
        )
    return "\n".join(lines) + "\n"


def _source_usage_counts(root: Path) -> dict[str, int]:
    counts: dict[str, int] = {}
    for kind in ("artifact", "accession", "task", "milestone", "reproduction", "snapshot"):
        for payload in _records_if_present(root, kind):
            value = payload.get("source_ids", [])
            if isinstance(value, list):
                for source_id in set(str(item) for item in value):
                    counts[source_id] = counts.get(source_id, 0) + 1
    return counts


def _source_summary(root: Path) -> str:
    if not (root / "sources").exists():
        return "# Sources\n\nNo source records yet.\n"
    usage_counts = _source_usage_counts(root)
    lines = [
        "# Sources",
        "",
        "| Source | Type | Confidence | Uses | Scope | URL |",
        "|---|---|---|---:|---|---|",
    ]
    for record in load_records(root, "source"):
        payload = record.payload
        lines.append(
            f"| {payload['title']} | {payload['source_type']} | {payload['confidence']} | "
            f"{usage_counts.get(str(payload['id']), 0)} | {payload['claim_scope']} | "
            f"{payload.get('url', '')} |"
        )
    return "\n".join(lines) + "\n"


def _accession_summary(root: Path) -> str:
    if not (root / "accessions").exists():
        return "# Accessions\n\nNo accession records yet.\n"
    lines = [
        "# Accessions",
        "",
        "| Artifact | Package | Capture | Fixity | Storage | Rights | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    records = sorted(
        load_records(root, "accession"),
        key=lambda record: (record.payload["artifact_id"], record.payload["id"]),
    )
    for record in records:
        payload = record.payload
        lines.append(
            f"| {payload['artifact_id']} | {payload['package_type']} | "
            f"{payload['capture_status']} | {payload['fixity_status']} | "
            f"{payload['storage_class']} | {payload['rights_review']} | {payload['public_notes']} |"
        )
    return "\n".join(lines) + "\n"


def _task_summary(root: Path) -> str:
    if not (root / "tasks").exists():
        return "# Tasks\n\nNo task records yet.\n"
    lines = [
        "# Tasks",
        "",
        "| Target | Task | Type | Status | Notes |",
        "|---|---|---|---|---|",
    ]
    records = sorted(
        load_records(root, "task"),
        key=lambda record: (record.payload["target_id"], record.payload["id"]),
    )
    for record in records:
        payload = record.payload
        lines.append(
            f"| {payload['target_id']} | {payload['id']} | {payload['task_type']} | "
            f"{payload['status']} | {payload['public_notes']} |"
        )
    return "\n".join(lines) + "\n"


def _milestone_summary(root: Path) -> str:
    if not (root / "milestones").exists():
        return "# Milestones\n\nNo milestone records yet.\n"
    lines = [
        "# Milestones",
        "",
        "| Target | Milestone | Type | Status | Evidence |",
        "|---|---|---|---|---|",
    ]
    records = sorted(
        load_records(root, "milestone"),
        key=lambda record: (record.payload["target_id"], record.payload["id"]),
    )
    for record in records:
        payload = record.payload
        lines.append(
            f"| {payload['target_id']} | {payload['id']} | {payload['milestone_type']} | "
            f"{payload['status']} | {payload['evidence']} |"
        )
    return "\n".join(lines) + "\n"


def _records_if_present(root: Path, kind: str) -> list[dict[str, object]]:
    directory = root / f"{kind}s"
    if kind == "accession":
        directory = root / "accessions"
    if not directory.exists():
        return []
    return [record.payload for record in load_records(root, kind)]


def _coverage_summary(root: Path) -> str:
    targets = _records_if_present(root, "target")
    sources = _records_if_present(root, "source")
    artifacts = _records_if_present(root, "artifact")
    accessions = _records_if_present(root, "accession")
    tasks = _records_if_present(root, "task")
    milestones = _records_if_present(root, "milestone")
    target_ids = {str(payload["id"]) for payload in targets}
    source_ids = {str(payload["id"]) for payload in sources}
    used_source_ids = {
        source_id for source_id, count in _source_usage_counts(root).items() if count > 0
    }
    task_target_ids = {str(payload["target_id"]) for payload in tasks}
    milestone_target_ids = {str(payload["target_id"]) for payload in milestones}
    artifact_ids = {str(payload["id"]) for payload in artifacts}
    accession_artifact_ids = {str(payload["artifact_id"]) for payload in accessions}
    accession_covered = len(artifact_ids & accession_artifact_ids)
    task_covered = len(target_ids & task_target_ids)
    milestone_covered = len(target_ids & milestone_target_ids)
    source_covered = len(source_ids & used_source_ids)
    missing_accessions = sorted(artifact_ids - accession_artifact_ids)
    missing_tasks = sorted(target_ids - task_target_ids)
    missing_milestones = sorted(target_ids - milestone_target_ids)
    unused_sources = sorted(source_ids - used_source_ids)
    lines = [
        "# Coverage",
        "",
        "| Metric | Covered | Total |",
        "|---|---:|---:|",
        f"| Artifact accession coverage | {accession_covered} | {len(artifact_ids)} |",
        f"| Target task coverage | {task_covered} | {len(target_ids)} |",
        f"| Target milestone coverage | {milestone_covered} | {len(target_ids)} |",
        f"| Source usage coverage | {source_covered} | {len(source_ids)} |",
        "",
        "| Record kind | Count |",
        "|---|---:|",
    ]
    for kind in (
        "target",
        "source",
        "artifact",
        "accession",
        "task",
        "milestone",
        "reproduction",
        "snapshot",
    ):
        lines.append(f"| {kind} | {len(_records_if_present(root, kind))} |")
    lines.extend(["", "## Missing Artifact Accessions", ""])
    if missing_accessions:
        lines.extend(f"- `{artifact_id}`" for artifact_id in missing_accessions)
    else:
        lines.append("No missing artifact accessions.")
    lines.extend(["", "## Missing Target Tasks", ""])
    if missing_tasks:
        lines.extend(f"- `{target_id}`" for target_id in missing_tasks)
    else:
        lines.append("No missing target tasks.")
    lines.extend(["", "## Missing Target Milestones", ""])
    if missing_milestones:
        lines.extend(f"- `{target_id}`" for target_id in missing_milestones)
    else:
        lines.append("No missing target milestones.")
    lines.extend(["", "## Unused Sources", ""])
    if unused_sources:
        lines.extend(f"- `{source_id}`" for source_id in unused_sources)
    else:
        lines.append("No unused sources.")
    return "\n".join(lines) + "\n"


def write_reports(root: Path) -> list[Path]:
    targets = build_target_index(root)
    generated = root / "docs" / "generated"
    sources_by_id = {
        str(payload["id"]): payload
        for payload in _records_if_present(root, "source")
    }
    written = [
        _write(generated / "index.md", "# Engine Revival Public Index\n\n" + render_target_table(targets)),
        _write(generated / "targets.md", "# Targets\n\n" + render_target_table(targets)),
        _write(generated / "rights-summary.md", _rights_summary(targets)),
        _write(generated / "sources.md", _source_summary(root)),
        _write(generated / "artifacts.md", _artifact_summary(root)),
        _write(generated / "accessions.md", _accession_summary(root)),
        _write(generated / "tasks.md", _task_summary(root)),
        _write(generated / "packets.md", packet_index(root)),
        _write(generated / "reproductions.md", reproduction_index(root)),
        _write(generated / "snapshots.md", snapshot_index(root)),
        _write(generated / "milestones.md", _milestone_summary(root)),
        _write(generated / "coverage.md", _coverage_summary(root)),
        _write_json(generated / "database.json", corpus_database(root)),
    ]
    for packet in packet_tasks(root):
        written.append(
            _write(
                generated / "packets" / f"{packet['id']}.md",
                packet_page(packet, sources_by_id),
            )
        )
    for reproduction in reproduction_records(root):
        written.append(
            _write(
                generated / "reproductions" / f"{reproduction['id']}.md",
                reproduction_page(reproduction, sources_by_id),
            )
        )
    for snapshot in snapshot_records(root):
        written.append(
            _write(
                generated / "snapshots" / f"{snapshot['id']}.md",
                snapshot_page(snapshot, sources_by_id),
            )
        )
    if (root / "targets").exists():
        for record in load_records(root, "target"):
            written.append(
                _write(
                    generated / "targets" / f"{record.payload['id']}.md",
                    target_dossier(root, record.payload),
                )
            )
    return written
